

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: checkin-exercito-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: checkin_exercito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - checkin-network

  # pgAdmin (Interface web para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: checkin-exercito-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@checkin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - checkin-network

  # Redis (para cache/sessões - opcional)
  redis:
    image: redis:7-alpine
    container_name: checkin-exercito-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - checkin-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local

networks:
  checkin-network:
    driver: bridge
