[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash scripts/start-production.sh"
