[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "DATABASE_URL='postgresql://dummy:dummy@localhost:5432/dummy?schema=public' npx prisma generate",
  "npm run build"
]

[start]
cmd = "bash scripts/start-production.sh"
